# Generated by Django 4.2.4 on 2023-09-05 00:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\s]*$', message='Introduzca solo letras, números y espacios en blanco')])),
                ('ruc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$', message='Introduzca solo numeros y un guion, sin puntos')])),
                ('nombre_contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Introduzca solo letras o espacios en blanco')])),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$', message='Introduzca solo numeros')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=50)),
                ('minimo', models.PositiveIntegerField()),
                ('unidades_stock', models.PositiveIntegerField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.material')),
            ],
            options={
                'verbose_name': 'material en pedido',
                'verbose_name_plural': 'materiales en pedido',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='fecha de fin')),
                ('estado', models.CharField(choices=[('NI', 'No iniciada'), ('E', 'En ejecución'), ('F', 'Finalizada')], default='NI', max_length=2, verbose_name='estado')),
                ('encargado', models.ForeignKey(limit_choices_to={'perfil__rol__nombre': 'INGENIERO'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='monto total')),
                ('estado', models.CharField(choices=[('E', 'En elaboración'), ('S', 'Enviado'), ('A', 'Aprobado')], default='E', max_length=1, verbose_name='estado')),
                ('encargado', models.ForeignKey(limit_choices_to={'perfil__rol__nombre': 'INGENIERO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\s]*$', message='Introduzca solo letras, números y espacios en blanco')])),
                ('ruc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$', message='Introduzca solo numeros y un guion, sin puntos')])),
                ('nombre_contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Introduzca solo letras o espacios en blanco')])),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$', message='Introduzca solo numeros')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('', ''), ('GERENTE', 'Gerente'), ('ADMINISTRADOR', 'Administrador'), ('INGENIERO', 'Ingeniero'), ('ENCARGADO_DEPOSITO', 'Encargado de Depósito')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente', verbose_name='cliente')),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.obra', verbose_name='obra')),
                ('presupuesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.presupuesto', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='fecha de solicitud')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado')], default='P', max_length=1, verbose_name='estado')),
                ('materiales', models.ManyToManyField(through='Aplicacion.MaterialPedido', to='Aplicacion.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.obra', verbose_name='obra')),
                ('solicitante', models.ForeignKey(limit_choices_to={'perfil__rol__nombre': 'INGENIERO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='materialpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.pedido'),
        ),
        migrations.AddField(
            model_name='material',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor'),
        ),
    ]
