# Generated by Django 4.1.7 on 2023-03-10 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\s]*$', message='Introduzca solo letras, números y espacios en blanco')])),
                ('ruc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$')])),
                ('nombre_contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$')])),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
