# Generated by Django 4.2.4 on 2023-09-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='obra',
            name='proyecto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proyecto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='proyecto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proyecto'),
        ),
    ]
