# Generated by Django 4.1.7 on 2023-03-10 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], default='L', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_contacto',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Introduzca solo letras o espacios en blanco')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_contacto',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$', message='Introduzca solo numeros')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$', message='Introduzca solo numeros y un guion, sin puntos')]),
        ),
    ]
