# Generated by Django 4.1.7 on 2023-03-10 19:33

import Aplicacion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_ingeniero_alter_cliente_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeniero',
            name='apellido',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras en el apellido.')]),
        ),
        migrations.AddField(
            model_name='ingeniero',
            name='nombre',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras en el nombre.')]),
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='fecha_nacimiento',
            field=models.DateField(help_text='La fecha de nacimiento no puede ser mayor a la fecha actual.', validators=[Aplicacion.models.validate_fecha_nacimiento]),
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'El formato de teléfono no es válido. Ejemplo: +541155555555.')]),
        ),
    ]
