# Generated by Django 4.2.4 on 2023-09-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_remove_proyecto_obra_remove_proyecto_presupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proyecto'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proyecto'),
        ),
    ]
