# Generated by Django 4.2.4 on 2023-09-05 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_obra_proyecto_alter_presupuesto_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='numero_contacto',
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Introduzca solo letras o espacios en blanco')])),
                ('numero', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$', message='Introduzca solo numeros')])),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor')),
            ],
        ),
    ]
