# Generated by Django 4.1.7 on 2023-03-10 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_ingeniero_apellido_ingeniero_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeniero',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras en el apellido.')]),
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Solo se permiten letras en el nombre.')]),
        ),
    ]
