# Generated by Django 4.1.7 on 2023-03-17 00:30

import Aplicacion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_alter_ingeniero_apellido_alter_ingeniero_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$', message='Introduzca solo numeros y un guion, sin puntos')])),
                ('nombre_contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Introduzca solo letras o espacios en blanco')])),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d]*$', message='Introduzca solo numeros')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='fecha_nacimiento',
            field=models.DateField(validators=[Aplicacion.models.validate_fecha_nacimiento]),
        ),
    ]
