# Generated by Django 4.1.7 on 2023-03-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
