# Generated by Django 4.2.4 on 2023-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_archivopresupuesto_categoria_item_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='precio_total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
