# Generated by Django 4.1.7 on 2023-03-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=50)),
                ('minimo', models.PositiveIntegerField()),
                ('unidades_stock', models.PositiveIntegerField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.proveedor')),
            ],
        ),
    ]
