# Generated by Django 4.2.4 on 2023-09-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_alter_subitem_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='anticipo',
            field=models.BooleanField(default=False, verbose_name='anticipo'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_anticipo',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='monto anticipo'),
        ),
    ]
