# Generated by Django 4.2.4 on 2023-09-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_obra_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='plazo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
