# Generated by Django 4.2.4 on 2023-09-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_alter_obra_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_pago_anticipo',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de pago del anticipo'),
        ),
    ]
