# Generated by Django 4.2 on 2023-10-03 21:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Aplicacion", "0011_presupuesto_fecha_pago_anticipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("P", "Presentado"), ("G", "Pagado")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "ingeniero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.presupuesto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.categoriacertificado",
                    ),
                ),
                (
                    "certificado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.certificado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="ciudad",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_persona",
            field=models.CharField(
                choices=[("Juridica", "Jurídica"), ("Fisica", "Física")],
                default="Fisica",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="ciudad",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="pagina_web",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\-]+\\.[\\w\\-]+(\\.[\\w\\-]+)?$",
                        message='La URL debe tener el formato "texto.texto" o "texto.texto.texto"',
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="SubItemCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("unidad_medida", models.CharField(max_length=50)),
                ("precio_total", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "certificado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.certificado",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.itemcertificado",
                    ),
                ),
                (
                    "subitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicacion.subitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categoriacertificado",
            name="certificado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Aplicacion.certificado"
            ),
        ),
    ]
