# Generated by Django 4.2.4 on 2024-06-07 22:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion', '0012_categoriacertificado_certificado_itemcertificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_culminacion', models.DateField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cronograma', to='Aplicacion.cronograma')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='fecha de solicitud')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='fecha de devolucion')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('D', 'Devuelto'), ('R', 'Rechazado')], default='P', max_length=1, verbose_name='estado')),
                ('ingeniero', models.ForeignKey(limit_choices_to=models.Q(('groupsname', 'INGENIERO')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'devolución',
                'verbose_name_plural': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDevuelto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('devolucion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.devolucion')),
                ('material', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.material')),
            ],
            options={
                'verbose_name': 'material devuelto',
                'verbose_name_plural': 'materiales devueltos',
            },
        ),
        migrations.CreateModel(
            name='MaterialPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.material')),
            ],
            options={
                'verbose_name': 'material en pedido de compra',
                'verbose_name_plural': 'materiales en pedido de compra',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='fecha de solicitud')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/compra')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Recibido')], default='P', max_length=1, verbose_name='estado')),
                ('materiales', models.ManyToManyField(through='Aplicacion.MaterialPedidoCompra', to='Aplicacion.material')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('secciones', models.ManyToManyField(blank=True, to='Aplicacion.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoriacertificado',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemcertificado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemcertificado',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subitemcertificado',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='subitemcertificado',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subitemcertificado',
            name='subitem',
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'certificado', 'verbose_name_plural': 'certificados'},
        ),
        migrations.RemoveField(
            model_name='archivopresupuesto',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='archivopresupuesto',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='archivopresupuesto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='fecha',
        ),
        migrations.AddField(
            model_name='certificado',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de creación del certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de envio del certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de pago del certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='monto total'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{6,20}$', message='Introduzca un teléfono válido (solo números entre 6 a 20 dígitos)')]),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='comprobante_anticipo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{6,20}$', message='Introduzca un teléfono válido (solo números entre 6 a 20 dígitos)')]),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente de envio'), ('S', 'Enviado'), ('A', 'Aprobado')], default='P', max_length=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='ingeniero',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'INGENIERO')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-]*$', message='Introduzca solo números y un guion, sin puntos')]),
        ),
        migrations.AlterField(
            model_name='obra',
            name='encargado',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'INGENIERO')), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='solicitante',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'INGENIERO')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='encargado',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'INGENIERO')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaCertificado',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemCertificado',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='SubItem',
        ),
        migrations.DeleteModel(
            name='SubItemCertificado',
        ),
        migrations.AddField(
            model_name='materialpedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.pedidocompra'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='materiales',
            field=models.ManyToManyField(null=True, through='Aplicacion.MaterialDevuelto', to='Aplicacion.material'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.obra', verbose_name='obra'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.pedido'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='subseccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.subseccion'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='archivo_presupuesto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.archivopresupuesto'),
        ),
        migrations.AddField(
            model_name='archivocertificado',
            name='certificado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.certificado'),
        ),
        migrations.AddField(
            model_name='archivocertificado',
            name='detalles',
            field=models.ManyToManyField(to='Aplicacion.detalle'),
        ),
        migrations.AddField(
            model_name='archivocertificado',
            name='secciones',
            field=models.ManyToManyField(to='Aplicacion.seccion'),
        ),
        migrations.AddField(
            model_name='archivocertificado',
            name='subsecciones',
            field=models.ManyToManyField(to='Aplicacion.subseccion'),
        ),
        migrations.AddField(
            model_name='archivopresupuesto',
            name='detalles',
            field=models.ManyToManyField(to='Aplicacion.detalle'),
        ),
        migrations.AddField(
            model_name='archivopresupuesto',
            name='secciones',
            field=models.ManyToManyField(to='Aplicacion.seccion'),
        ),
        migrations.AddField(
            model_name='archivopresupuesto',
            name='subsecciones',
            field=models.ManyToManyField(to='Aplicacion.subseccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ciudad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.marca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ciudad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ciudad'),
        ),
    ]
