# Generated by Django 4.2.4 on 2024-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0013_archivocertificado_ciudad_cronograma_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCiudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datamart.dim_ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ciudad_id', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datamart.dim_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca_id', models.IntegerField()),
                ('medida_id', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('unidades_stock', models.IntegerField()),
                ('fotografia', models.CharField(max_length=255)),
                ('id_proveedor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'datamart.dim_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ciudad_id', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('pagina_web', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'datamart.dim_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cliente_id', models.IntegerField()),
                ('ciudad_id', models.IntegerField()),
            ],
            options={
                'db_table': 'datamart.dim_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimUsuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField()),
            ],
            options={
                'db_table': 'datamart.dim_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoCertificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingeniero_id', models.IntegerField()),
                ('presupuesto_id', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('fecha_envio', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'datamart.hecho_certificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoDevolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingeniero_id', models.IntegerField()),
                ('obra_id', models.IntegerField()),
                ('pedido_id', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datamart.hecho_devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoEstadoIngeniero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingeniero_id', models.IntegerField()),
                ('nombre_ingeniero', models.CharField(max_length=100)),
                ('cantidad_obras_ejecucion', models.IntegerField()),
                ('cantidad_presupuestos_elaboracion', models.IntegerField()),
            ],
            options={
                'db_table': 'datamart.hecho_estado_ingeniero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoMaterialPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_id', models.IntegerField()),
                ('material_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datamart.hecho_materialpedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obra_id', models.IntegerField()),
                ('solicitante_id', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datamart.hecho_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechoPresupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('encargado_id', models.IntegerField()),
                ('proyecto_id', models.IntegerField()),
                ('anticipo', models.BooleanField()),
                ('monto_anticipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago_anticipo', models.DateField()),
                ('comprobante_anticipo', models.CharField(max_length=255)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'datamart.hecho_presupuesto',
                'managed': False,
            },
        ),
    ]
