# Generated by Django 4.2.4 on 2024-06-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0014_dimciudad_dimcliente_dimmaterial_dimproveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hechoestadoingeniero',
            table='hecho_estado_ingeniero',
        ),
    ]
