# Generated by Django 4.2.4 on 2024-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0016_alter_dimciudad_table_alter_dimcliente_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoMaterialPorObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obra_id', models.IntegerField()),
                ('material_id', models.IntegerField()),
                ('cantidad_total', models.IntegerField(default=0)),
                ('obra_nombre', models.CharField(max_length=255)),
                ('material_nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hechomaterialporobra',
                'managed': False,
            },
        ),
    ]
