# Generated by Django 4.2.4 on 2024-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0017_hechomaterialporobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronograma_id', models.IntegerField()),
                ('detalle_id', models.IntegerField()),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_culminacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hechocronograma',
                'managed': False,
            },
        ),
    ]
