# Generated by Django 4.2.4 on 2024-06-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0018_hechocronograma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechosProyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ingeniero', models.IntegerField()),
                ('cantidad_presupuestos', models.IntegerField()),
                ('cantidad_obras', models.IntegerField()),
                ('cantidad_pedidos', models.IntegerField()),
                ('cantidad_devoluciones', models.IntegerField()),
            ],
            options={
                'db_table': 'hechos_proyectos',
                'managed': False,
            },
        ),
    ]
