# Generated by Django 4.2.4 on 2024-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0020_hechorecuento_delete_hechosproyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_obra', models.IntegerField()),
                ('id_encargado', models.IntegerField()),
                ('estado', models.CharField(max_length=2)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datamart.hecho_obra',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HechoRecuento',
        ),
    ]
