# Generated by Django 4.2.4 on 2024-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0021_hechoobra_delete_hechorecuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha de asignación'),
        ),
    ]
